services:
  - type: web
    name: flask-todo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:APP
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
