services:
  - type: web
    name: flask-todo-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:APP
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flask-todo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ITEMS_PER_PAGE
        value: 20
      - key: LOG_LEVEL
        value: INFO